export type LedgerErrorCode =
  | "ACCOUNT_NOT_FOUND"
  | "ACCOUNT_NAME_INVALID"
  | "ACCOUNT_NAME_DUPLICATE"
  | "ACCOUNT_ID_DUPLICATE"
  | "ACCOUNT_PARENT_INVALID"
  | "ACCOUNT_PARENT_NOT_PLACEHOLDER"
  | "ACCOUNT_TYPE_MISMATCH"
  | "ACCOUNT_CYCLE"
  | "ACCOUNT_HAS_CHILDREN"
  | "ACCOUNT_HAS_POSTINGS"
  | "ACCOUNT_IS_PLACEHOLDER"
  | "ACCOUNT_IS_SYSTEM"
  | "ACCOUNT_CURRENCY_LOCKED"
  | "ACCOUNT_TYPE_LOCKED"
  | "INVALID_CURRENCY_CODE"
  | "ENTRY_NOT_FOUND"
  | "ENTRY_ID_DUPLICATE"
  | "ENTRY_TOO_FEW_POSTINGS"
  | "ENTRY_TOO_FEW_ACCOUNTS"
  | "ENTRY_AMOUNT_INVALID"
  | "ENTRY_DATE_INVALID"
  | "ENTRY_UNBALANCED"
  | "ENTRY_FX_CURRENCY_COUNT"
  | "ENTRY_FX_RATE_MISMATCH"
  | "ENTRY_OPENING_MUST_BE_SINGLE_CURRENCY"
  | "POSTING_ACCOUNT_CURRENCY_MISMATCH"
  | "BOOK_NAME_INVALID"
  | "BOOK_INVALID_SCHEMA_VERSION"
  | "BOOK_INVALID"
  | "JSON_PARSE_FAILED"
  | "JSON_INVALID_BOOK"
  | "STORAGE_UNAVAILABLE"
  | "STORAGE_WRITE_FAILED"
  | "FILE_READ_FAILED";

export interface LedgerError {
  code: LedgerErrorCode;
  message: string;
  details?: Record<string, unknown>;
}
